Repository woo00oo/goGetterProjectServer, pull requests merged in 2021-07, with the labels that each got.

#82 [Event Create] 이벤트 등록 API 구현
  src/main/java/udodog/goGetterServer/controller/api/event/EventController.java
  src/main/java/udodog/goGetterServer/model/converter/event/EventConverter.java
  src/main/java/udodog/goGetterServer/model/dto/request/event/EventCreateRequestDto.java
  src/main/java/udodog/goGetterServer/model/entity/Event.java
  src/main/java/udodog/goGetterServer/service/event/EventService.java
  src/test/java/udodog/goGetterServer/controller/api/event/EventControllerTest.java
  src/test/java/udodog/goGetterServer/repository/EventRepositoryTest.java
  src/test/java/udodog/goGetterServer/service/event/EventServiceTest.java
Labels: 🏗️ Type : Test, 🏷️Sever, 👷 Type : Feature / Function, 💥 Priority : High, 📝 Type : Feature / Document

#90 [progress-event-find-all] 진행중인 이벤트 전체 조회 API 구현
  src/main/java/udodog/goGetterServer/controller/api/SessionController.java
  src/main/java/udodog/goGetterServer/controller/api/event/EventController.java
  src/main/java/udodog/goGetterServer/model/converter/event/EventConverter.java
  src/main/java/udodog/goGetterServer/model/dto/response/event/ProgressEventsResponseDto.java
  src/main/java/udodog/goGetterServer/model/dto/response/user/UserSignInResponseDto.java
  src/main/java/udodog/goGetterServer/repository/querydsl/EventQueryRepository.java
  src/main/java/udodog/goGetterServer/service/event/EventService.java
  src/main/java/udodog/goGetterServer/service/user/SessionService.java
  src/main/java/udodog/goGetterServer/service/user/UserService.java
  src/test/java/udodog/goGetterServer/config/TestConfig.java
  src/test/java/udodog/goGetterServer/controller/api/event/EventControllerTest.java
  src/test/java/udodog/goGetterServer/repository/querydsl/EventQueryRepositoryTest.java
  src/test/java/udodog/goGetterServer/service/event/EventServiceTest.java
Labels: 🏷️Sever, 👷 Type : Feature / Function, 💥 Priority : Medium, 📝 Type : Feature / Document

#92 [End-Events-all-find] 종료된 이벤트 전체 조회 API 구현
  src/main/java/udodog/goGetterServer/controller/api/event/EventController.java
  src/main/java/udodog/goGetterServer/model/converter/event/EventConverter.java
  src/main/java/udodog/goGetterServer/model/dto/response/event/EventsResponseDto.java
  src/main/java/udodog/goGetterServer/repository/querydsl/EventQueryRepository.java
  src/main/java/udodog/goGetterServer/service/event/EventService.java
  src/test/java/udodog/goGetterServer/repository/querydsl/EventQueryRepositoryTest.java
  src/test/java/udodog/goGetterServer/service/event/EventServiceTest.java
Labels: 🏷️Sever, 👷 Type : Feature / Function, 💥 Priority : Medium, 📝 Type : Feature / Document

#105 feat #103 : 토론게시판 Refectoring
  build.gradle
  src/main/java/udodog/goGetterServer/config/WebMvcConfig.java
  src/main/java/udodog/goGetterServer/controller/api/discussion/DiscussionController.java
  src/main/java/udodog/goGetterServer/controller/api/discussion/DiscussionReplyController.java
  src/main/java/udodog/goGetterServer/model/converter/discussion/DiscussionConvertor.java
  src/main/java/udodog/goGetterServer/model/converter/discussion/DiscussionListConvertor.java
  src/main/java/udodog/goGetterServer/model/converter/discussion/DiscussionReplyConvertor.java
  src/main/java/udodog/goGetterServer/model/converter/discussion/DiscussionReplyListConvertor.java
  src/main/java/udodog/goGetterServer/model/dto/request/discussion/DiscussionEditRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/discussion/DiscussionInsertRequestDto.java
  src/main/java/udodog/goGetterServer/model/dto/request/discussion/DiscussionReplyEditRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/discussion/DiscussionReplyInsertRequest.java
  src/main/java/udodog/goGetterServer/model/dto/response/discussion/DiscussionDetailResponse.java
  src/main/java/udodog/goGetterServer/model/dto/response/discussion/DiscussionReplyResponse.java
  src/main/java/udodog/goGetterServer/model/dto/response/discussion/DiscussionReseponseDto.java
  src/main/java/udodog/goGetterServer/model/entity/DiscussionBoard.java
  src/main/java/udodog/goGetterServer/model/entity/DiscussionBoardReadhit.java
  src/main/java/udodog/goGetterServer/model/entity/DiscussionBoardReply.java
  src/main/java/udodog/goGetterServer/repository/DiscussionBoardReadhitRepository.java
  src/main/java/udodog/goGetterServer/repository/DiscussionBoardReplyRepository.java
  src/main/java/udodog/goGetterServer/repository/DiscussionBoardRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/DiscussionBoardQueryRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/DiscussionBoardReadhitQueryRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/DiscussionBoardReplyQueryRepository.java
  src/main/java/udodog/goGetterServer/service/discussion/DiscussionReplyService.java
  src/main/java/udodog/goGetterServer/service/discussion/DiscussionService.java
Labels: ♻️ Type : Refactoring, 🏷️Sever, 📄 Status : Duplicated

#117 [Event-Delete] 이벤트 삭제 API
  src/main/java/udodog/goGetterServer/controller/api/event/EventController.java
  src/main/java/udodog/goGetterServer/model/converter/event/EventConverter.java
  src/main/java/udodog/goGetterServer/service/event/EventService.java
  src/test/java/udodog/goGetterServer/controller/api/event/EventControllerTest.java
  src/test/java/udodog/goGetterServer/service/event/EventServiceTest.java
Labels: 🏗️ Type : Test, 🏷️Sever, 👷 Type : Feature / Function, 📝 Type : Feature / Document

#120 Refactor #103 : 토론게시판 API Refactoring
  src/main/java/udodog/goGetterServer/controller/api/discussion/DiscussionController.java
  src/main/java/udodog/goGetterServer/controller/api/discussion/DiscussionReplyController.java
  src/main/java/udodog/goGetterServer/model/converter/discussion/DiscussionConverter.java
  src/main/java/udodog/goGetterServer/model/converter/discussion/DiscussionListConverter.java
  src/main/java/udodog/goGetterServer/model/converter/discussion/DiscussionReplyConvertor.java
  src/main/java/udodog/goGetterServer/model/converter/discussion/DiscussionReplyListConverter.java
  src/main/java/udodog/goGetterServer/model/dto/request/discussion/DiscussionEditRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/discussion/DiscussionReplyEditRequest.java
  src/main/java/udodog/goGetterServer/model/dto/response/discussion/DiscussionDetailResponse.java
  src/main/java/udodog/goGetterServer/model/dto/response/discussion/DiscussionReplyResponse.java
  src/main/java/udodog/goGetterServer/model/dto/response/discussion/DiscussionResponseDto.java
  src/main/java/udodog/goGetterServer/repository/querydsl/DiscussionBoardQueryRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/DiscussionBoardReplyQueryRepository.java
  src/main/java/udodog/goGetterServer/service/discussion/DiscussionReplyService.java
  src/main/java/udodog/goGetterServer/service/discussion/DiscussionService.java
Labels: ♻️ Type : Refactoring, 🏷️Sever, 📄 Status : Duplicated

#123 Refactor #97 : 공유 게시판 Refactoring
  src/main/java/udodog/goGetterServer/controller/api/sharingboard/SharingBoardController.java
  src/main/java/udodog/goGetterServer/controller/api/sharingboard/SharingBoardLikeController.java
  src/main/java/udodog/goGetterServer/controller/api/sharingboard/SharingBoardWeeklyBestController.java
  src/main/java/udodog/goGetterServer/controller/api/sharingboard/SharingReplyController.java
  src/main/java/udodog/goGetterServer/model/converter/sharingboard/SharingConverter.java
  src/main/java/udodog/goGetterServer/model/converter/sharingboard/SharingListConverter.java
  src/main/java/udodog/goGetterServer/model/converter/sharingboard/SharingReplyConverter.java
  src/main/java/udodog/goGetterServer/model/dto/request/UpdateSharingReplyRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/sharingboard/CreateBoardRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/sharingboard/CreateSharingReplyRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/sharingboard/DeleteSharingReplyRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/sharingboard/LikeUserRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/sharingboard/UpdateBoardRequest.java
  src/main/java/udodog/goGetterServer/model/dto/response/sharingboard/BoardResponse.java
  src/main/java/udodog/goGetterServer/model/dto/response/sharingboard/SharingReplyResponse.java
  src/main/java/udodog/goGetterServer/model/dto/response/sharingboard/SimpleBoardResponse.java
  src/main/java/udodog/goGetterServer/model/dto/response/sharingboard/WriterInfo.java
  src/main/java/udodog/goGetterServer/model/entity/SharingBoard.java
  src/main/java/udodog/goGetterServer/model/entity/SharingBoardLike.java
  src/main/java/udodog/goGetterServer/model/entity/SharingBoardReply.java
  src/main/java/udodog/goGetterServer/repository/SharingBoardLikeRepository.java
  src/main/java/udodog/goGetterServer/repository/SharingBoardReplyRepository.java
  src/main/java/udodog/goGetterServer/repository/SharingBoardRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/sharingboard/SharingBoardExtension.java
  src/main/java/udodog/goGetterServer/repository/querydsl/sharingboard/SharingBoardExtensionImpl.java
  src/main/java/udodog/goGetterServer/service/sharingboard/SharingBoardLikeService.java
  src/main/java/udodog/goGetterServer/service/sharingboard/SharingBoardService.java
  src/main/java/udodog/goGetterServer/service/sharingboard/SharingBoardWeeklyBestService.java
  src/main/java/udodog/goGetterServer/service/sharingboard/SharingReplyService.java
  src/main/java/udodog/goGetterServer/service/user/UserService.java
  src/test/java/udodog/goGetterServer/controller/api/sharingboard/SharingBoardControllerTest.java
  src/test/java/udodog/goGetterServer/repository/SharingBoardReplyRepositoryTest.java
  src/test/java/udodog/goGetterServer/repository/SharingBoardRepositoryTest.java
  src/test/java/udodog/goGetterServer/repository/SharingBoardSharingBoardLikeRepositoryTest.java
Labels: ♻️ Type : Refactoring, 🏷️Sever, 👷 Type : Feature / Function, 📝 Type : Feature / Document

#95 #Feat 94: 공유 게시판 댓글 조회, 등록, 수정, 삭제 API 구현
  src/main/java/udodog/goGetterServer/controller/api/sharingboard/SharingBoardController.java
  src/main/java/udodog/goGetterServer/controller/api/sharingboard/SharingBoardLikeController.java
  src/main/java/udodog/goGetterServer/controller/api/sharingboard/SharingBoardWeeklyBestController.java
  src/main/java/udodog/goGetterServer/controller/api/sharingboard/SharingReplyController.java
  src/main/java/udodog/goGetterServer/model/converter/sharingboard/SharingConverter.java
  src/main/java/udodog/goGetterServer/model/converter/sharingboard/SharingListConverter.java
  src/main/java/udodog/goGetterServer/model/converter/sharingboard/SharingReplyConverter.java
  src/main/java/udodog/goGetterServer/model/dto/request/UpdateSharingReplyRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/sharingboard/CreateBoardRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/sharingboard/CreateSharingReplyRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/sharingboard/DeleteSharingReplyRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/sharingboard/LikeUserRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/sharingboard/UpdateBoardRequest.java
  src/main/java/udodog/goGetterServer/model/dto/response/sharingboard/BoardResponse.java
  src/main/java/udodog/goGetterServer/model/dto/response/sharingboard/SharingReplyResponse.java
  src/main/java/udodog/goGetterServer/model/dto/response/sharingboard/SimpleBoardResponse.java
  src/main/java/udodog/goGetterServer/model/dto/response/sharingboard/WriterInfo.java
  src/main/java/udodog/goGetterServer/model/entity/SharingBoard.java
  src/main/java/udodog/goGetterServer/model/entity/SharingBoardLike.java
  src/main/java/udodog/goGetterServer/model/entity/SharingBoardReply.java
  src/main/java/udodog/goGetterServer/repository/SharingBoardLikeRepository.java
  src/main/java/udodog/goGetterServer/repository/SharingBoardReplyRepository.java
  src/main/java/udodog/goGetterServer/repository/SharingBoardRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/sharingboard/SharingBoardExtension.java
  src/main/java/udodog/goGetterServer/repository/querydsl/sharingboard/SharingBoardExtensionImpl.java
  src/main/java/udodog/goGetterServer/service/sharingboard/SharingBoardLikeService.java
  src/main/java/udodog/goGetterServer/service/sharingboard/SharingBoardService.java
  src/main/java/udodog/goGetterServer/service/sharingboard/SharingBoardWeeklyBestService.java
  src/main/java/udodog/goGetterServer/service/sharingboard/SharingReplyService.java
  src/main/java/udodog/goGetterServer/service/user/UserService.java
  src/test/java/udodog/goGetterServer/controller/api/sharingboard/SharingBoardControllerTest.java
  src/test/java/udodog/goGetterServer/repository/SharingBoardReplyRepositoryTest.java
  src/test/java/udodog/goGetterServer/repository/SharingBoardRepositoryTest.java
  src/test/java/udodog/goGetterServer/repository/SharingBoardSharingBoardLikeRepositoryTest.java
Labels: 🏷️Sever, 👷 Type : Feature / Function, 📝 Type : Feature / Document

#136 [events-refactoring] 이벤트 상세조회 N+1 리펙토링
  src/main/java/udodog/goGetterServer/controller/api/coupon/CouponController.java
  src/main/java/udodog/goGetterServer/model/dto/request/coupon/CouponCreateRequestDto.java
  src/main/java/udodog/goGetterServer/repository/CouponUseHistoryRepository.java
  src/main/java/udodog/goGetterServer/repository/EventRepository.java
  src/main/java/udodog/goGetterServer/service/coupon/CouponService.java
  src/test/java/udodog/goGetterServer/controller/api/coupon/CouponControllerTest.java
  src/test/java/udodog/goGetterServer/repository/CouponUseHistoryRepositoryTest.java
  src/test/java/udodog/goGetterServer/repository/EventRepositoryTest.java
  src/test/java/udodog/goGetterServer/service/coupon/CouponServiceTest.java
Labels: ♻️ Type : Refactoring, 🏗️ Type : Test, 🏷️Sever

#133 Feat #119, #127 MyPage API, 아이디, 비밀번호 찾기 API 구현
  src/main/java/udodog/goGetterServer/controller/api/mypage/MyPageController.java
  src/main/java/udodog/goGetterServer/controller/api/user/UserController.java
  src/main/java/udodog/goGetterServer/model/converter/mypage/MyPageConverter.java
  src/main/java/udodog/goGetterServer/model/converter/user/UserConverter.java
  src/main/java/udodog/goGetterServer/model/dto/request/mypage/MyPageRequestDto.java
  src/main/java/udodog/goGetterServer/model/dto/request/user/UserFindEmailRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/user/UserFindPwdRequest.java
  src/main/java/udodog/goGetterServer/model/dto/response/mypage/MyPageResponseDto.java
  src/main/java/udodog/goGetterServer/model/dto/response/user/UserFindEmailResponseDto.java
  src/main/java/udodog/goGetterServer/repository/querydsl/MyPageQueryRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/UserQueryRepository.java
  src/main/java/udodog/goGetterServer/service/mypage/MyPageService.java
  src/main/java/udodog/goGetterServer/service/user/UserService.java
  src/test/java/udodog/goGetterServer/service/user/UserServiceTest.java
Labels: 🏷️Sever, 👷 Type : Feature / Function, 📝 Type : Feature / Document

#137 Feat #135: 공유 게시판 태그 API 구현
  src/main/java/udodog/goGetterServer/model/dto/request/sharingboard/CreateBoardRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/sharingboard/UpdateBoardRequest.java
  src/main/java/udodog/goGetterServer/model/dto/response/sharingboard/BoardResponse.java
  src/main/java/udodog/goGetterServer/model/entity/SharingBoardTag.java
  src/main/java/udodog/goGetterServer/repository/SharingBoardReplyRepository.java
  src/main/java/udodog/goGetterServer/repository/SharingBoardTagRepository.java
  src/main/java/udodog/goGetterServer/service/sharingboard/SharingBoardService.java
  src/test/java/udodog/goGetterServer/repository/SharingBoardTagRepositoryTest.java
Labels: 🏷️Sever, 👷 Type : Feature / Function, 📝 Type : Feature / Document

#141 Refactor #140 : 독서 기록 게시판 URI 수정 및 Bug 수정
  src/main/java/udodog/goGetterServer/controller/api/bookreport/BookReportController.java
  src/main/java/udodog/goGetterServer/model/dto/request/bookreporttag/BookReportTagInsertRequestDto.java
  src/main/java/udodog/goGetterServer/model/dto/response/bookreport/BookReportDetailResponseDto.java
  src/main/java/udodog/goGetterServer/model/dto/response/bookreport/BookreportResponseDto.java
  src/main/java/udodog/goGetterServer/model/entity/BookReport.java
  src/main/java/udodog/goGetterServer/model/entity/BookReportTag.java
  src/main/java/udodog/goGetterServer/repository/querydsl/BookReportQueryRepository.java
  src/main/java/udodog/goGetterServer/service/bookreport/BookreportService.java
Labels: ♻️ Type : Refactoring, 🏷️Sever, 👷 Type : Feature / Function, 💥 Priority : Critical, 📄 Status : InProgress

#148 Refactor #147: 공유 게시판 리팩토링
  src/main/java/udodog/goGetterServer/model/dto/response/sharingboard/SimpleBoardResponse.java
  src/main/java/udodog/goGetterServer/service/sharingboard/SharingBoardService.java
  src/test/java/udodog/goGetterServer/repository/SharingBoardRepositoryTest.java
Labels: ♻️ Type : Refactoring, 🏷️Sever, 💥 Priority : High

#146 Refactor #103 토론게시판 Refactoring
  src/main/java/udodog/goGetterServer/model/dto/request/discussion/DiscussionEditRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/discussion/DiscussionInsertRequestDto.java
  src/main/java/udodog/goGetterServer/model/dto/request/discussion/DiscussionReplyEditRequest.java
  src/main/java/udodog/goGetterServer/model/dto/response/discussion/DiscussionDetailResponse.java
  src/main/java/udodog/goGetterServer/model/dto/response/discussion/DiscussionReplyResponse.java
  src/main/java/udodog/goGetterServer/model/dto/response/discussion/DiscussionResponseDto.java
  src/main/java/udodog/goGetterServer/model/entity/DiscussionBoard.java
  src/main/java/udodog/goGetterServer/model/entity/DiscussionBoardReply.java
  src/main/java/udodog/goGetterServer/repository/querydsl/DiscussionBoardQueryRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/DiscussionBoardReplyQueryRepository.java
  src/test/java/udodog/goGetterServer/controller/api/discussion/DiscussionControllerTest.java
Labels: ♻️ Type : Refactoring, ✅ Status : Done, 🏷️Sever

#152 [Message-send] 쪽지 발송 API 구현
  src/main/java/udodog/goGetterServer/controller/api/message/MessageSenderController.java
  src/main/java/udodog/goGetterServer/model/dto/request/message/MessageSenderRequestDto.java
  src/main/java/udodog/goGetterServer/model/entity/Message.java
  src/main/java/udodog/goGetterServer/service/message/MessageSenderService.java
  src/test/java/udodog/goGetterServer/controller/api/message/MessageSenderControllerTest.java
  src/test/java/udodog/goGetterServer/service/message/MessageSenderServiceTest.java
Labels: 🏗️ Type : Test, 🏷️Sever, 👷 Type : Feature / Function, 📝 Type : Feature / Document

#153 Refactor #103: 토론게시판 Refactoring
  src/test/java/udodog/goGetterServer/controller/api/discussion/DiscussionControllerTest.java
  src/test/java/udodog/goGetterServer/controller/api/discussion/DiscussionReplyControllerTest.java
Labels: ♻️ Type : Refactoring, ✅ Status : Done, 🏷️Sever

#156 Feat #155 : 쪽지 알림 API 구현
  src/main/java/udodog/goGetterServer/controller/api/message/MessageNotificationController.java
  src/main/java/udodog/goGetterServer/controller/api/sharingboard/SharingReplyController.java
  src/main/java/udodog/goGetterServer/model/dto/request/message/MessageNotificationRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/sharingboard/CreateBoardRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/sharingboard/UpdateSharingReplyRequest.java
  src/main/java/udodog/goGetterServer/model/dto/response/message/MessageNotificationResponse.java
  src/main/java/udodog/goGetterServer/model/dto/response/sharingboard/SharingReplyResponse.java
  src/main/java/udodog/goGetterServer/model/dto/response/sharingboard/SimpleBoardResponse.java
  src/main/java/udodog/goGetterServer/model/entity/SharingBoardReply.java
  src/main/java/udodog/goGetterServer/repository/MessageRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/message/MessageNotificationExtension.java
  src/main/java/udodog/goGetterServer/repository/querydsl/message/MessageNotificationExtensionImpl.java
  src/main/java/udodog/goGetterServer/service/message/MessageNotificationService.java
  src/main/java/udodog/goGetterServer/service/sharingboard/SharingReplyService.java
Labels: 🏷️Sever, 👷 Type : Feature / Function, 📝 Type : Feature / Document

#158 Refactor #103 Feat #119 : 토론게시판 Refactoring, 마이페이지 API
  src/main/java/udodog/goGetterServer/controller/api/discussion/DiscussionController.java
  src/main/java/udodog/goGetterServer/controller/api/discussion/DiscussionReplyController.java
  src/main/java/udodog/goGetterServer/controller/api/mypage/MyPageController.java
  src/main/java/udodog/goGetterServer/service/discussion/DiscussionReplyService.java
  src/main/java/udodog/goGetterServer/service/discussion/DiscussionService.java
  src/main/java/udodog/goGetterServer/service/mypage/MyPageService.java
  src/test/java/udodog/goGetterServer/controller/api/discussion/DiscussionControllerTest.java
  src/test/java/udodog/goGetterServer/controller/api/discussion/DiscussionReplyControllerTest.java
Labels: ♻️ Type : Refactoring, ✅ Status : Done, 🏷️Sever

#165 Feat #163 : Manager Page 회원 전체 조회, Black 회원 조회 기능 구현
  src/main/java/udodog/goGetterServer/controller/api/manager/UserManagementController.java
  src/main/java/udodog/goGetterServer/model/converter/manager/ManagerConverter.java
  src/main/java/udodog/goGetterServer/model/converter/manager/ManagerPagingConverter.java
  src/main/java/udodog/goGetterServer/model/dto/response/manager/search/UserSearchResponseDto.java
  src/main/java/udodog/goGetterServer/model/entity/User.java
  src/main/java/udodog/goGetterServer/repository/querydsl/UserQueryRepository.java
  src/main/java/udodog/goGetterServer/service/manager/UserSearchService.java
  src/test/java/udodog/goGetterServer/repository/UserRepositoryTest.java
Labels: 🏷️Sever, 👷 Type : Feature / Function, 💥 Priority : Critical

#164 Chore #162 : Manager Page 관련 Repository Test 최신화
  src/test/java/udodog/goGetterServer/repository/UserRepositoryTest.java
Labels: 🏗️ Type : Test, 🏷️Sever, 👷 Type : Feature / Function, 💥 Priority : High

#171 Refactor #170 : SharingBoardReplyRepositoryTest 리팩토링
  src/main/java/udodog/goGetterServer/model/dto/request/sharingboard/UpdateBoardRequest.java
  src/main/java/udodog/goGetterServer/service/sharingboard/SharingBoardService.java
  src/test/java/udodog/goGetterServer/repository/SharingBoardReplyRepositoryTest.java
  src/test/java/udodog/goGetterServer/repository/SharingBoardRepositoryTest.java
Labels: ♻️ Type : Refactoring, 🏷️Sever

#181 Feat #166, #167, #168, #169, #172, #173, #174,#175 #179: 관리자 Page 요구사항 분석 의거 모든 기능 구현 완료
  src/main/java/udodog/goGetterServer/controller/api/manager/UserManagementController.java
  src/main/java/udodog/goGetterServer/model/converter/manager/ManagerConverter.java
  src/main/java/udodog/goGetterServer/model/converter/manager/ManagerListConverter.java
  src/main/java/udodog/goGetterServer/model/converter/manager/ManagerPagingConverter.java
  src/main/java/udodog/goGetterServer/model/dto/request/manager/MemberJoinCountRequestDto.java
  src/main/java/udodog/goGetterServer/model/dto/request/manager/MemberUpdateGradeRequestDto.java
  src/main/java/udodog/goGetterServer/model/dto/response/manager/search/UserSearchResponseDto.java
  src/main/java/udodog/goGetterServer/model/dto/response/manager/visuallization/MemberJoinVisuallizationResponseDto.java
  src/main/java/udodog/goGetterServer/repository/querydsl/UserQueryRepository.java
  src/main/java/udodog/goGetterServer/service/manager/UserSearchService.java
Labels: 🏷️Sever, 👷 Type : Feature / Function, 💥 Priority : High

#183 Refactor #182 : 전국 도서관 정보 기능 Domain Layer 및 Repository Test 재 구성
  build.gradle
  src/main/java/udodog/goGetterServer/controller/api/bookreport/BookReportController.java
  src/main/java/udodog/goGetterServer/controller/api/nationwidelibraryinfo/NationwideLibraryInfoController.java
  src/main/java/udodog/goGetterServer/model/converter/bookreport/BookReportConverter.java
  src/main/java/udodog/goGetterServer/model/converter/nationwidelibraryinfo/NationwidelibraryInfoConverter.java
  src/main/java/udodog/goGetterServer/model/converter/nationwidelibraryinfo/NationwidelibraryInfoPagingConverter.java
  src/main/java/udodog/goGetterServer/model/converter/nationwidelibraryinfo/NationwidelibraryLocationInfoPagingConverter.java
  src/main/java/udodog/goGetterServer/model/dto/request/nationwidelibraryinfo/NationwideLibraryInfoInsertReqeustDto.java
  src/main/java/udodog/goGetterServer/model/dto/request/nationwidelibraryinfo/NationwideLibraryInfoUpdateReqeustDto.java
  src/main/java/udodog/goGetterServer/model/dto/response/nationwidelibraryinfo/NationwidelibraryInfoDetailResponseDto.java
  src/main/java/udodog/goGetterServer/model/dto/response/nationwidelibraryinfo/NationwidelibraryInfoResponseDto.java
  src/main/java/udodog/goGetterServer/model/dto/response/nationwidelibraryinfo/visualization/NationwidelibraryInfoVisualizationDto.java
  src/main/java/udodog/goGetterServer/model/entity/LibraryLocation.java
  src/main/java/udodog/goGetterServer/model/entity/NationwideLibraryInfo.java
  src/main/java/udodog/goGetterServer/repository/BookReportRepository.java
  src/main/java/udodog/goGetterServer/repository/LibraryLocationRepository.java
  src/main/java/udodog/goGetterServer/repository/NationwideLibraryInfoRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/bookReport/BookReportQueryRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/bookReport/BookReportTagQueryRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/nationwidelibraryInfo/NationwidelibraryInfoQueryRepository.java
  src/main/java/udodog/goGetterServer/service/bookreport/BookreportService.java
  src/main/java/udodog/goGetterServer/service/nationwidelibraryinfo/NationwidelibraryInfoService.java
  src/test/java/udodog/goGetterServer/repository/LibraryLocationRepositoryTest.java
  src/test/java/udodog/goGetterServer/repository/NationwideLibraryInfoRepositoryTest.java
Labels: ♻️ Type : Refactoring, 🏷️Sever, 💥 Priority : Critical

#198 Feat #160 Oauth2.0 소셜로그인(Google, Facebook) API 구현
  .gitignore
  build.gradle
  src/main/java/udodog/goGetterServer/controller/api/oauth/OauthController.java
  src/main/java/udodog/goGetterServer/model/converter/oauth/OauthConverter.java
  src/main/java/udodog/goGetterServer/model/converter/oauth/SocialLoginTypeConverter.java
  src/main/java/udodog/goGetterServer/model/entity/User.java
  src/main/java/udodog/goGetterServer/model/entity/UserConnection.java
  src/main/java/udodog/goGetterServer/model/enumclass/oauth/SocialLoginType.java
  src/main/java/udodog/goGetterServer/repository/DiscussionBoardReadhitRepository.java
  src/main/java/udodog/goGetterServer/repository/DiscussionBoardReplyRepository.java
  src/main/java/udodog/goGetterServer/repository/UserConnectionRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/UserQueryRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/disccussion/DiscussionBoardQueryRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/disccussion/DiscussionBoardReadhitQueryRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/disccussion/DiscussionBoardReplyQueryRepository.java
  src/main/java/udodog/goGetterServer/repository/querydsl/oauth/UserConnectionQueryRepository.java
  src/main/java/udodog/goGetterServer/service/oauth/OauthService.java
  src/main/java/udodog/goGetterServer/service/oauth/social/FacebookOauth.java
  src/main/java/udodog/goGetterServer/service/oauth/social/GoogleOauth.java
  src/main/java/udodog/goGetterServer/service/oauth/social/SocialOauth.java
  src/main/java/udodog/goGetterServer/service/user/UserService.java
Labels: 🏷️Sever, 👷 Type : Feature / Function, 💥 Priority : High, 📄 Status : InProgress, 🚧 Type : Dependency

#202 Refactor #199 : Manager Page 회원가입 시각화 관련
  src/main/java/udodog/goGetterServer/controller/api/manager/UserManagementController.java
  src/main/java/udodog/goGetterServer/repository/querydsl/UserQueryRepository.java
  src/main/java/udodog/goGetterServer/service/manager/UserSearchService.java
Labels: ♻️ Type : Refactoring, 🏷️Sever, 💥 Priority : Critical

#206 Feat #160 Oauth2.0 소셜로그인(Google, Facebook) API 구현
  src/main/java/udodog/goGetterServer/controller/api/oauth/OauthController.java
  src/main/java/udodog/goGetterServer/model/converter/oauth/OauthConverter.java
  src/main/java/udodog/goGetterServer/repository/querydsl/UserQueryRepository.java
  src/main/java/udodog/goGetterServer/service/oauth/OauthService.java
  src/main/java/udodog/goGetterServer/service/oauth/social/FacebookOauth.java
  src/main/java/udodog/goGetterServer/service/oauth/social/GoogleOauth.java
Labels: 🏷️Sever, 💥 Priority : High, 📄 Status : InProgress
