Repository woo00oo/goGetterProjectServer, pull requests merged in 2021-06, with the labels that each got.

#20 Default Response 구현
  build.gradle
  src/main/java/udodog/goGetterServer/GoGetterServerApplication.java
  src/main/java/udodog/goGetterServer/config/JpaAuditingConfig.java
  src/main/java/udodog/goGetterServer/config/SwaggerConfig.java
  src/main/java/udodog/goGetterServer/controller/HelloController.java
  src/main/java/udodog/goGetterServer/controller/SampleController.java
  src/main/java/udodog/goGetterServer/model/converter/EntityToModelConvertor.java
  src/main/java/udodog/goGetterServer/model/dto/DefaultRes.java
  src/main/java/udodog/goGetterServer/model/dto/Pagination.java
  src/test/java/udodog/goGetterServer/controller/SampleControllerTest.java
Labels: 🏷️Sever, 👷 Type : Feature / Function, 💥 Priority : High, 📄 Status : ToDoIssues

#22 스프링 시큐리티 설정
  build.gradle
  src/main/java/udodog/goGetterServer/config/SpringSecurityConfig.java
Labels: 👷 Type : Feature / Function, 💥 Priority : High, 🚧 Type : Dependency

#32 회원가입 API 구현
  .gitignore
  build.gradle
  src/main/java/udodog/goGetterServer/config/SpringAsyncConfig.java
  src/main/java/udodog/goGetterServer/config/SwaggerConfig.java
  src/main/java/udodog/goGetterServer/controller/ExceptionAdvisor.java
  src/main/java/udodog/goGetterServer/controller/api/user/UserController.java
  src/main/java/udodog/goGetterServer/model/converter/user/UserConverter.java
  src/main/java/udodog/goGetterServer/model/dto/request/UserSignUpRequestDto.java
  src/main/java/udodog/goGetterServer/model/utils/MailHandler.java
  src/main/java/udodog/goGetterServer/repository/UserRepository.java
  src/main/java/udodog/goGetterServer/service/user/UserService.java
  src/main/resources/static/go-getter.jpg
  src/test/java/udodog/goGetterServer/controller/api/user/UserControllerTest.java
  src/test/java/udodog/goGetterServer/service/user/UserServiceTest.java
Labels: 🏷️Sever, 👷 Type : Feature / Function, 💥 Priority : High, 📝 Type : Documentation, 🚧 Type : Dependency

#29 Chore #28 : ModelMapper 의존성 추가 및 테스트
  .gitignore
  build.gradle
  src/main/java/udodog/goGetterServer/config/ModelMapperConfig.java
  src/main/java/udodog/goGetterServer/config/SpringAsyncConfig.java
  src/main/java/udodog/goGetterServer/config/SwaggerConfig.java
  src/main/java/udodog/goGetterServer/controller/SampleController.java
  src/main/java/udodog/goGetterServer/controller/api/user/UserController.java
  src/main/java/udodog/goGetterServer/model/converter/EntityToModelConvertor.java
  src/main/java/udodog/goGetterServer/model/dto/ModelMapperTestDTO.java
  src/main/java/udodog/goGetterServer/model/utils/MailHandler.java
  src/main/java/udodog/goGetterServer/repository/UserRepository.java
  src/main/java/udodog/goGetterServer/service/user/UserService.java
  src/main/resources/static/go-getter.jpg
Labels: 🏷️Sever, 🚧 Type : Dependency

#46 [Jwt Token] Jwt 의존성 추가, Util 클래스 구현
  build.gradle
  src/main/java/udodog/goGetterServer/config/SpringSecurityConfig.java
  src/main/java/udodog/goGetterServer/model/utils/JwtUtil.java
Labels: 🏷️Sever, 💥 Priority : High, 📄 Status : ToDoIssues, 🚧 Type : Dependency

#75 refactor #27, #33, #44, #57, #58: 토론게시판 API 구현
  src/main/java/udodog/goGetterServer/config/ModelMapperConfig.java
  src/main/java/udodog/goGetterServer/controller/api/discussion/DiscussionController.java
  src/main/java/udodog/goGetterServer/model/converter/discussion/DiscussionConvertor.java
  src/main/java/udodog/goGetterServer/model/converter/discussion/DiscussionListConvertor.java
  src/main/java/udodog/goGetterServer/model/dto/request/discussion/DiscussionEditRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/discussion/DiscussionInsertRequestDto.java
  src/main/java/udodog/goGetterServer/model/dto/response/discussion/DiscussionDetailResponse.java
  src/main/java/udodog/goGetterServer/model/dto/response/discussion/DiscussionReseponseDto.java
  src/main/java/udodog/goGetterServer/model/entity/DiscussionBoard.java
  src/main/java/udodog/goGetterServer/model/entity/DiscussionBoardReply.java
  src/main/java/udodog/goGetterServer/repository/DiscussonBoardReplyRepository.java
  src/main/java/udodog/goGetterServer/repository/DiscussonBoardRepository.java
  src/main/java/udodog/goGetterServer/service/discussion/DiscussionService.java
  src/main/java/udodog/goGetterServer/service/user/UserService.java
Labels: ♻️ Type : Refactoring, 🏷️Sever, 📄 Status : InProgress

#77 [Jwt-Authorization] 인터셉터를 활용한 JWT 인가처리
  src/main/java/udodog/goGetterServer/config/WebMvcConfig.java
  src/main/java/udodog/goGetterServer/controller/interceptor/AdmApiInterceptor.java
  src/main/java/udodog/goGetterServer/controller/interceptor/BkUserApiInterceptor.java
  src/main/java/udodog/goGetterServer/controller/interceptor/UserApiInterceptor.java
  src/main/java/udodog/goGetterServer/model/dto/response/user/JwtAccessTokenResponse.java
  src/main/java/udodog/goGetterServer/model/utils/JwtUtil.java
  src/main/java/udodog/goGetterServer/service/user/SessionService.java
Labels: 🏷️Sever, 👷 Type : Feature / Function, 💥 Priority : Critical

#80 feat #27, #33, #44, #57, #58, #63, #64, #73, #76, #78: 토론게시판, 토론게시판 댓글, 토론게시판 검색 API 구현
  src/main/java/udodog/goGetterServer/controller/api/discussion/DiscussionController.java
  src/main/java/udodog/goGetterServer/controller/api/discussion/DiscussionReplyController.java
  src/main/java/udodog/goGetterServer/model/converter/discussion/DiscussionListConvertor.java
  src/main/java/udodog/goGetterServer/model/converter/discussion/DiscussionReplyConvertor.java
  src/main/java/udodog/goGetterServer/model/converter/discussion/DiscussionReplyListConvertor.java
  src/main/java/udodog/goGetterServer/model/dto/request/discussion/DiscussionReplyEditRequest.java
  src/main/java/udodog/goGetterServer/model/dto/request/discussion/DiscussionReplyInsertRequest.java
  src/main/java/udodog/goGetterServer/model/dto/response/discussion/DiscussionReplyResponse.java
  src/main/java/udodog/goGetterServer/model/dto/response/discussion/DiscussionReseponseDto.java
  src/main/java/udodog/goGetterServer/model/entity/DiscussionBoard.java
  src/main/java/udodog/goGetterServer/model/entity/DiscussionBoardReadhit.java
  src/main/java/udodog/goGetterServer/repository/DiscussionBoardReadhitRepository.java
  src/main/java/udodog/goGetterServer/repository/DiscussionBoardReplyRepository.java
  src/main/java/udodog/goGetterServer/repository/DiscussionBoardRepository.java
  src/main/java/udodog/goGetterServer/repository/DiscussonBoardReadhitRepository.java
  src/main/java/udodog/goGetterServer/repository/DiscussonBoardRepository.java
  src/main/java/udodog/goGetterServer/service/discussion/DiscussionReplyService.java
  src/main/java/udodog/goGetterServer/service/discussion/DiscussionService.java
  src/test/java/udodog/goGetterServer/repository/DiscussonBoardReadhitRepositoryTest.java
  src/test/java/udodog/goGetterServer/repository/DiscussonBoardReplyRepositoryTest.java
  src/test/java/udodog/goGetterServer/repository/DiscussonBoardRepositoryTest.java
Labels: ♻️ Type : Refactoring, 🏷️Sever, 👷 Type : Feature / Function, 📄 Status : InProgress
